/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as HuisKopenInSlowakijeRouteImport } from './routes/huis-kopen-in-slowakije'
import { Route as HuisKopenInTsjechieRouteImport } from './routes/huis-kopen-in-tsjechie'
import { Route as OnsNetwerkRouteImport } from './routes/ons-netwerk'
import { Route as OnsVerhaalRouteImport } from './routes/ons-verhaal'
import { Route as ProjectenRouteImport } from './routes/projecten'
import { Route as RegelsEnWetgevingRouteImport } from './routes/regels-en-wetgeving'
import { Route as VoorbeeldenHuizenRouteImport } from './routes/voorbeelden-huizen'
import { Route as WaaromSlowakijeRouteImport } from './routes/waarom-slowakije'
import { Route as WaaromTsjechieRouteImport } from './routes/waarom-tsjechie'
import { Route as ZoWerkenWijRouteImport } from './routes/zo-werken-wij'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const HuisKopenInSlowakijeRoute = HuisKopenInSlowakijeRouteImport.update({
  id: '/huis-kopen-in-slowakije',
  path: '/huis-kopen-in-slowakije',
  getParentRoute: () => rootRouteImport,
} as any)
const HuisKopenInTsjechieRoute = HuisKopenInTsjechieRouteImport.update({
  id: '/huis-kopen-in-tsjechie',
  path: '/huis-kopen-in-tsjechie',
  getParentRoute: () => rootRouteImport,
} as any)
const OnsNetwerkRoute = OnsNetwerkRouteImport.update({
  id: '/ons-netwerk',
  path: '/ons-netwerk',
  getParentRoute: () => rootRouteImport,
} as any)
const OnsVerhaalRoute = OnsVerhaalRouteImport.update({
  id: '/ons-verhaal',
  path: '/ons-verhaal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenRoute = ProjectenRouteImport.update({
  id: '/projecten',
  path: '/projecten',
  getParentRoute: () => rootRouteImport,
} as any)
const RegelsEnWetgevingRoute = RegelsEnWetgevingRouteImport.update({
  id: '/regels-en-wetgeving',
  path: '/regels-en-wetgeving',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorbeeldenHuizenRoute = VoorbeeldenHuizenRouteImport.update({
  id: '/voorbeelden-huizen',
  path: '/voorbeelden-huizen',
  getParentRoute: () => rootRouteImport,
} as any)
const WaaromSlowakijeRoute = WaaromSlowakijeRouteImport.update({
  id: '/waarom-slowakije',
  path: '/waarom-slowakije',
  getParentRoute: () => rootRouteImport,
} as any)
const WaaromTsjechieRoute = WaaromTsjechieRouteImport.update({
  id: '/waarom-tsjechie',
  path: '/waarom-tsjechie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoWerkenWijRoute = ZoWerkenWijRouteImport.update({
  id: '/zo-werken-wij',
  path: '/zo-werken-wij',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/huis-kopen-in-slowakije': typeof HuisKopenInSlowakijeRoute
  '/huis-kopen-in-tsjechie': typeof HuisKopenInTsjechieRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/regels-en-wetgeving': typeof RegelsEnWetgevingRoute
  '/voorbeelden-huizen': typeof VoorbeeldenHuizenRoute
  '/waarom-slowakije': typeof WaaromSlowakijeRoute
  '/waarom-tsjechie': typeof WaaromTsjechieRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/huis-kopen-in-slowakije': typeof HuisKopenInSlowakijeRoute
  '/huis-kopen-in-tsjechie': typeof HuisKopenInTsjechieRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/regels-en-wetgeving': typeof RegelsEnWetgevingRoute
  '/voorbeelden-huizen': typeof VoorbeeldenHuizenRoute
  '/waarom-slowakije': typeof WaaromSlowakijeRoute
  '/waarom-tsjechie': typeof WaaromTsjechieRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/huis-kopen-in-slowakije': typeof HuisKopenInSlowakijeRoute
  '/huis-kopen-in-tsjechie': typeof HuisKopenInTsjechieRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/regels-en-wetgeving': typeof RegelsEnWetgevingRoute
  '/voorbeelden-huizen': typeof VoorbeeldenHuizenRoute
  '/waarom-slowakije': typeof WaaromSlowakijeRoute
  '/waarom-tsjechie': typeof WaaromTsjechieRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/huis-kopen-in-slowakije'
    | '/huis-kopen-in-tsjechie'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/regels-en-wetgeving'
    | '/voorbeelden-huizen'
    | '/waarom-slowakije'
    | '/waarom-tsjechie'
    | '/zo-werken-wij'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/huis-kopen-in-slowakije'
    | '/huis-kopen-in-tsjechie'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/regels-en-wetgeving'
    | '/voorbeelden-huizen'
    | '/waarom-slowakije'
    | '/waarom-tsjechie'
    | '/zo-werken-wij'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/huis-kopen-in-slowakije'
    | '/huis-kopen-in-tsjechie'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/regels-en-wetgeving'
    | '/voorbeelden-huizen'
    | '/waarom-slowakije'
    | '/waarom-tsjechie'
    | '/zo-werken-wij'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  HuisKopenInSlowakijeRoute: typeof HuisKopenInSlowakijeRoute
  HuisKopenInTsjechieRoute: typeof HuisKopenInTsjechieRoute
  OnsNetwerkRoute: typeof OnsNetwerkRoute
  OnsVerhaalRoute: typeof OnsVerhaalRoute
  ProjectenRoute: typeof ProjectenRoute
  RegelsEnWetgevingRoute: typeof RegelsEnWetgevingRoute
  VoorbeeldenHuizenRoute: typeof VoorbeeldenHuizenRoute
  WaaromSlowakijeRoute: typeof WaaromSlowakijeRoute
  WaaromTsjechieRoute: typeof WaaromTsjechieRoute
  ZoWerkenWijRoute: typeof ZoWerkenWijRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huis-kopen-in-slowakije': {
      id: '/huis-kopen-in-slowakije'
      path: '/huis-kopen-in-slowakije'
      fullPath: '/huis-kopen-in-slowakije'
      preLoaderRoute: typeof HuisKopenInSlowakijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huis-kopen-in-tsjechie': {
      id: '/huis-kopen-in-tsjechie'
      path: '/huis-kopen-in-tsjechie'
      fullPath: '/huis-kopen-in-tsjechie'
      preLoaderRoute: typeof HuisKopenInTsjechieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ons-netwerk': {
      id: '/ons-netwerk'
      path: '/ons-netwerk'
      fullPath: '/ons-netwerk'
      preLoaderRoute: typeof OnsNetwerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ons-verhaal': {
      id: '/ons-verhaal'
      path: '/ons-verhaal'
      fullPath: '/ons-verhaal'
      preLoaderRoute: typeof OnsVerhaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten': {
      id: '/projecten'
      path: '/projecten'
      fullPath: '/projecten'
      preLoaderRoute: typeof ProjectenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regels-en-wetgeving': {
      id: '/regels-en-wetgeving'
      path: '/regels-en-wetgeving'
      fullPath: '/regels-en-wetgeving'
      preLoaderRoute: typeof RegelsEnWetgevingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorbeelden-huizen': {
      id: '/voorbeelden-huizen'
      path: '/voorbeelden-huizen'
      fullPath: '/voorbeelden-huizen'
      preLoaderRoute: typeof VoorbeeldenHuizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waarom-slowakije': {
      id: '/waarom-slowakije'
      path: '/waarom-slowakije'
      fullPath: '/waarom-slowakije'
      preLoaderRoute: typeof WaaromSlowakijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waarom-tsjechie': {
      id: '/waarom-tsjechie'
      path: '/waarom-tsjechie'
      fullPath: '/waarom-tsjechie'
      preLoaderRoute: typeof WaaromTsjechieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zo-werken-wij': {
      id: '/zo-werken-wij'
      path: '/zo-werken-wij'
      fullPath: '/zo-werken-wij'
      preLoaderRoute: typeof ZoWerkenWijRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  HuisKopenInSlowakijeRoute: HuisKopenInSlowakijeRoute,
  HuisKopenInTsjechieRoute: HuisKopenInTsjechieRoute,
  OnsNetwerkRoute: OnsNetwerkRoute,
  OnsVerhaalRoute: OnsVerhaalRoute,
  ProjectenRoute: ProjectenRoute,
  RegelsEnWetgevingRoute: RegelsEnWetgevingRoute,
  VoorbeeldenHuizenRoute: VoorbeeldenHuizenRoute,
  WaaromSlowakijeRoute: WaaromSlowakijeRoute,
  WaaromTsjechieRoute: WaaromTsjechieRoute,
  ZoWerkenWijRoute: ZoWerkenWijRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
