/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as OnsNetwerkRouteImport } from './routes/ons-netwerk'
import { Route as OnsVerhaalRouteImport } from './routes/ons-verhaal'
import { Route as ProjectenRouteImport } from './routes/projecten'
import { Route as ZoWerkenWijRouteImport } from './routes/zo-werken-wij'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const OnsNetwerkRoute = OnsNetwerkRouteImport.update({
  id: '/ons-netwerk',
  path: '/ons-netwerk',
  getParentRoute: () => rootRouteImport,
} as any)
const OnsVerhaalRoute = OnsVerhaalRouteImport.update({
  id: '/ons-verhaal',
  path: '/ons-verhaal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenRoute = ProjectenRouteImport.update({
  id: '/projecten',
  path: '/projecten',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoWerkenWijRoute = ZoWerkenWijRouteImport.update({
  id: '/zo-werken-wij',
  path: '/zo-werken-wij',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ons-netwerk': typeof OnsNetwerkRoute
  '/ons-verhaal': typeof OnsVerhaalRoute
  '/projecten': typeof ProjectenRoute
  '/zo-werken-wij': typeof ZoWerkenWijRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/zo-werken-wij'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/zo-werken-wij'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/ons-netwerk'
    | '/ons-verhaal'
    | '/projecten'
    | '/zo-werken-wij'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  OnsNetwerkRoute: typeof OnsNetwerkRoute
  OnsVerhaalRoute: typeof OnsVerhaalRoute
  ProjectenRoute: typeof ProjectenRoute
  ZoWerkenWijRoute: typeof ZoWerkenWijRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ons-netwerk': {
      id: '/ons-netwerk'
      path: '/ons-netwerk'
      fullPath: '/ons-netwerk'
      preLoaderRoute: typeof OnsNetwerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ons-verhaal': {
      id: '/ons-verhaal'
      path: '/ons-verhaal'
      fullPath: '/ons-verhaal'
      preLoaderRoute: typeof OnsVerhaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten': {
      id: '/projecten'
      path: '/projecten'
      fullPath: '/projecten'
      preLoaderRoute: typeof ProjectenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zo-werken-wij': {
      id: '/zo-werken-wij'
      path: '/zo-werken-wij'
      fullPath: '/zo-werken-wij'
      preLoaderRoute: typeof ZoWerkenWijRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  OnsNetwerkRoute: OnsNetwerkRoute,
  OnsVerhaalRoute: OnsVerhaalRoute,
  ProjectenRoute: ProjectenRoute,
  ZoWerkenWijRoute: ZoWerkenWijRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
